---
- name: Install Docker and Deploy Flask Application
  hosts: ec2app
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker and Docker Compose plugin
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create app directory on target EC2
      file:
        path: /home/ubuntu/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy application files to server
      copy:
        src: app/
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu

    - name: Build and start container using Docker Compose
      command: docker compose up -d --build
      args:
        chdir: /home/ubuntu/app
    - name: Install java
      apt:
        name: openjdk-21-jre
        state: present

    - name: Download Jenkins GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins.list


    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started